// Default training corpus used to build the demo vocabulary at server startup.
// In a real system this would be a large text dataset; here it's kept small
// and readable on purpose so the tokenizer's behavior is easy to inspect.
export const DEFAULT_CORPUS: string[] = [
  "Hello world, this is a custom tokenizer built from scratch.",
  "It supports word level, character level, and subword BPE tokenization modes.",
  "Tokenization is the first step before feeding text into a language model.",
  "A vocabulary maps every token to a unique integer id.",
  "Byte pair encoding learns to merge frequent adjacent symbol pairs.",
  "Common words like hi, hello, yes, and no are protected and never split.",
  "The encoder converts raw text into a list of tokens and token ids.",
  "The decoder converts token ids back into the original text exactly.",
  "Whitespace is preserved using a leading space marker on each token.",
  "This project demonstrates systems design and natural language processing.",
  "Raghav is building a full stack application with Next.js and TypeScript.",
  "The frontend sends text to the backend through a REST API endpoint.",
  "The backend trains a tokenizer once and reuses it across requests.",
  "Unknown words that were never seen during training map to a special token.",
  "Thank you for trying out this interactive tokenizer playground.",
  "The quick brown fox jumps over the lazy dog while the sun sets behind the hills.",
  "Data scientists compare models, metrics, and training losses in everyday experiments.",
  "Subword units help handle rare words like transformer, multilingual, and pretraining.",
  "Numbers like 2024, 3.14, and 100% appear often in real documents and logs.",
  "Punctuation such as commas, semicolons, quotes, and parentheses should be tokenized consistently.",
  "MixedCase names like GitHub, iPhone, and eBay should remain recognizable.",
  "Hyphenated terms such as state-of-the-art and full-stack are common in technical writing.",
  "English contractions including don't, can't, and we're are useful training examples.",
  "A tokenizer can split on whitespace, punctuation, or learned subword boundaries.",
  "Neural networks learn representations from large corpora of natural language.",
  "Some words repeat often, while others are rare and benefit from subword merging.",
  "The model uses embeddings, attention, and feedforward layers to understand context.",
  "Did you know? Wow! Quartz, Jazz, Vex, Fizz, and Kix can be fun to say.",
  "JQKXZ and VFX make a quirky, jazzy mix of capital letters in a sentence!",
  "Why is Quartz so quick? Fizz and Jazz are very vibrant!",
  "Vexing Kix with QXJ seems odd, but it works surprisingly well.",
  "Zany foxes and jolly quails enjoy vivid sunsets in January!",
  "Fjords, quartz, and viking myths can be weirdly fascinating to explore.",
  "Kangaroos, jacks, and vexed quokkas zoom through the jungle?",
];
